### ISSUE TITLE
Google Oauth login says "Project Default Service Account"

### ISSUE THREAD

**Issue by typpo** [mldangelo/mldangelo#25]
![image](https://cloud.githubusercontent.com/assets/310310/24594064/169b0e98-17de-11e7-91fa-b26315a2cbf1.png)

**Comment by mldangelo** [comment]
Fixed! Thanks for the bug report.

**Comment by AndroidDeveloperLB** [comment]
@mldangelo What is the URL (for developers) to change this default name of "project default service account" ?
